apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: weather-app
  labels:
    app: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: debilyator/nextjs:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "http://go-api-service:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
          initialDelaySeconds: 60  # Увеличил задержку для Next.js
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /  # Проверяем главную страницу
            port: 3000
          initialDelaySeconds: 30  # Next.js нужно больше времени на старт
          periodSeconds: 5
          timeoutSeconds: 3