apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: weather-app
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream go-api {
            server go-api-service:8000;
        }

        upstream nextjs {
            server nextjs-service:3000;
        }

        server {
            listen 80;
            server_name _;

            # Frontend - Next.js
            location / {
                proxy_pass http://nextjs;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Для Next.js
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_cache_bypass $http_upgrade;
            }

            # Backend API
            location /api/ {
                proxy_pass http://go-api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # CORS headers
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
                
                if ($request_method = 'OPTIONS') {
                    return 204;
                }
            }

            # Health checks
            location /health {
                proxy_pass http://nextjs/health;
                proxy_set_header Host $host;
            }
        }
    }
