apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: app/nextjs:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-env
          command: ["/bin/sh"]
          args: ["-c", "npm run build && npm start -H 0.0.0.0 -p 3000"]
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs
  namespace: app
spec:
  selector:
    app: nextjs
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
