version: '3.8'

services:
  go-api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nextjs:
    build:
      context: ./front/FE_WeatherTime
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
