apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  namespace: weather-app
spec:
  selector:
    app: go-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP