name: Deploy to VPS

on:
  push:
    branches: [ master ] 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Проверяем код
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Настраиваем SSH на раннере (временной машине GitHub Actions)
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    # 3. Добавляем сервер в известные хосты (избегаем вопроса о доверии)
    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    # 4. Выполняем команды на нашем сервере через SSH
    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "
          cd /root/weather-time
          git pull origin main
          docker-compose up --build
        "
